import Head from "next/head";
import Link from 'next/link';
import Footer from "@/components/Footer";
import { use, useState } from "react";
import { donate, getCampaign } from "@/services/Web3Service";
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Create() {

  const [campaign, setCampaign] = useState({});
  const [donation, setDonation] = useState(0);
  const [message, setMessage] = useState("");
  const [status, setStatus] = useState(false);

  function back() {
    setStatus(true);
  }

  function onChangeId(evt) {
    console.log(campaign.id);
    campaign.id = evt.target.value;
  }

  function btnSearchClick() {
    setMessage("Buscando... aguarde...");
    getCampaign(campaign.id)
      .then(result => {
        setMessage("");
        result.id = campaign.id;
        setStatus(false);
        setCampaign(result);
      })
      .catch(err => {
        console.error(err);
        setMessage(err.message);
      });
  }

  function onChangeId(evt) {
    campaign.id = evt.target.value;
  }

  function onChangeValue(evt) {
    setDonation(evt.target.value);
  }

  function btnDonateClick() {
    setMessage("Doando... aguarde...");
    donate(campaign.id, donation)
      .then(tx => setMessage('Doação realizada, obrigado! Em alguns minutos o saldo será atualizado.'))
      .catch(err => {
        console.error(err);
        setMessage(err.message);
      });
  }

  return (
    <>
      <Head>
        <title>Donate Crypto | Doar</title>
        <meta charSet='utf-8' />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1 className='display-4 fw-bold text-body-emphasis lh-1 mb-3'>Donate Crypto</h1>
        {
          status || !campaign.id
            ? (
              <>
                <p className="mb-5">Qual é o ID da campanha que procura?</p>
                <div className="col-3">
                  <div className="input-group mb-3">
                    <input type="number" id="campaignId" min="0" className="form-control" onChange={onChangeId} />
                    <input type="button" value="Buscar" id="campaignId" className="btn btn-primary p-3" onClick={btnSearchClick} />
                  </div>
                </div>
              </>
            )
            : (
              <>
                <p>Verifique se esta é a campanha certa antes de finalizar sua doação.</p>
                <hr />
                <div className="row flex-lg-row-reverse align-items-center g-5">
                  <div className="col-7">
                    {
                      campaign.videoUrl
                        ? <iframe width="100%" height="480" src={campaign.videoUrl}></iframe>
                        : <img src={campaign.imageUrl} className="d-block mx-lg-auto img-fluid" width="640" height="480" />
                    }
                  </div>
                  <div className="col-5 mb-5" style={{height: 480, scrollbars: true}}>
                    <h2>{campaign.title}</h2>
                    <p><strong>Autor:</strong> {campaign.author}</p>
                    <p className="mb-3">{campaign.description}</p>
                    {
                      campaign.videoUrl
                        ? <p>Assista o vídeo ao lado para entender mais sobre nossa campanha.</p>
                        : <></>
                    }
                    <p className="mb-3 fst-italic mt-5">E aí, o que achou do projeto? Já foi arrecadado <strong>{campaign.balance /10 ** 18} BNB</strong> nesta campanha.</p>
                    <p>Quanto você quer doar?</p>
                    <div className="mb-3">
                      <div className="input-group">
                        <input type="number" id="donation" min="0" step="0.000001" className="form-control" onChange={onChangeValue} value={donation} />
                        <span className="input-group-text">BNB</span>
                        <input type="button" value="Doar" id="campaignId" className="btn btn-primary p-3 w-25" onClick={btnDonateClick} />
                      </div>
                    </div>
                    <div className='mb-3'>
                      <input type="button" value="Buscar outra campanha" id="campaignId" className="btn btn-secondary col-12 p-3" onClick={back} />
                    </div>
                  </div>
                </div>
              </>
            )
        }
        {
          message
            ? <div className="alert alert-success p-3 col-6" role="alert">{message}</div>
            : <></>
        }
        <Footer />
      </div>
    </>
  )
}