import { useState } from 'react';
import Head from 'next/head';
import Footer from '@/components/Footer';
import { doLogin } from '@/services/Web3Service';
import { userAgent } from 'next/server';

export default function Home() {

  const [wallet, setWallet] = useState("");
  const [error, setError] = useState("");

  function btnLoginClick() {
    doLogin()
      .then(wallet => setWallet(wallet))
      .catch(err => setError(err.message));
  }

  return (
    <>
      <Head>
        <title>Donate Crypto | Index</title>
        <meta charSet='utf-8' />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"></link>
      </Head>
      <main className='container px-4 py-5'>
        <div className='row flex-lg-row-reverse align-items-center py-5 g-5'>
          <div className='col-10 col-sm-8 col-lg-6'>
            <img src='https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80' className='d-block mx-lg-auto img-fluid' width={700} height={500}/>
          </div>
          <div className='col-lg-6'>
            <h1 className='display-4 fw-bold text-body-emphasis lh-1 mb-3'>Donate Crypto</h1>
            <p className='lead'>Sua plataforma descentralizada de doações</p>
            <p className='kead mb-3'>Autentique-se com sua carteira, crie sua campanha ou doe para campnhas existentes</p>
            <div className='d-grid gap-2 d-md-flex justify-content-md-start'>
              <button type='button' className='col-12 btn btn-success btn-lg px-4 me-md-2' onClick={btnLoginClick}>
                <img src='/metamask.svg' width={64} className='me-3'/>
                Conectar com a MetaMask
              </button>
            </div>
            <div className='d-grid gap-2 d-md-flex justify-content-md-start'>
                { `Wallet ID: ${error || wallet}`}
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  )
}
